#include <config.h>
#include "pch-seek.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <psrxml.h>
#include <fftw3.h>
#include <getopt.h>
#include <math.h>

void pch_seek_help(); /*generated by make_options_code.py in pch-seek-options.C */
void pch_seek_help_hidden(); /*generated by make_options_code.py in pch-seek-options.C */
void pch_seek_optargs(int* nopt, struct option*, int *opt_flag); /*generated by make_options_code.py in pch-seek-options.C */

/**
 * PulsarCHunter SEEK
 *
 * This is a program for finding pulsars.
 *
 * This 'main' method doesn't really do anything,
 * just read the file and calls the 'do_search' function 
 * which calls the various search commands.
 *
 * 2008-12-22	M.Keith		Initial version
 *
 */
int main(int argc, char** argv){

	float** data_array;
	psrxml* header;
	FILE *dmfile;
	int dmtrials_size;
	int threads=0;
	int long_opt_idx = 0;
	int scrunch_factor=1;
	int fft_size = -1;
	char harmbuf[512];
	pch_seek_operations_t operations;

	header = (psrxml*) malloc(sizeof (psrxml));

	dmfile=NULL;

	pch_seek_init_operations(&operations);

#include "pch-seek-options.h"

	if (operations.nharms > 0){
		// this is a little difficult to work out!
		// (because C is for monkeys)
		char* end;
		char* str;
		int val;
		int i,arrlen;
		arrlen=8;
		i=0;
		operations.harmfolds=(int*)malloc(sizeof(int)*arrlen);
		str=harmbuf;
		end=str+strlen(str);
		while (str<end){
			if (i > arrlen){
				arrlen*=2;
				operations.harmfolds=(int*)realloc(operations.harmfolds,(sizeof(int)*arrlen));
			}
			sscanf(str,"%d",&val);
			operations.harmfolds[i]=val;
			i++;
			while(str[0] != ' ' && str[0] !='\0')str++;
			str++;
		}
		operations.nharms=i;
	}

	// Options are now read!
	// Now we read the psrxml file

	if (optind >= argc) {
		printf("Error: Need a psrxml file to work on... (use --help for options)\n");
		for(int  i=0; i < long_opt_idx ; i++){
			printf("%s\n",long_opt[i].name);
		}
		exit(1);
	}

	readPsrXml(header, argv[optind]);


	if(fft_size == 0){
		// auto-use a good size fft!
		fft_size=pch_seek_fourier_size(header->numberOfSamples,0);
	}

	if(fft_size > 1){
		// we pretend the file is shorter than it is to force the size to be sensible
		int read_length = (int)fft_size*scrunch_factor;
		printf("Only using first %d samples of file\n",read_length);
		if (read_length < header->numberOfSamples){
			header->numberOfSamples = read_length;
			header->actualObsTime=read_length*header->currentSampleInterval;
		}

	}

	/*
	 * If we are using a 'dm file' to specify some dispersion measures to use
	 * read them in now.
	 *
	 * This is used by the phase-search algorithm only at the moment.
	 *
	 */
	if(dmfile!=NULL){
		dmtrials_size = 10;
		operations.dmtrials = (float*)malloc(sizeof(float)*dmtrials_size);
		operations.ndm=0;
		while(!feof(dmfile)){
			if (operations.ndm > dmtrials_size){	
				dmtrials_size*=2;
				operations.dmtrials=(float*)realloc(operations.dmtrials,sizeof(float)*dmtrials_size);
			}
			fscanf(dmfile,"%f\n",operations.dmtrials+operations.ndm);
			operations.ndm++;
		}
		printf("Using %d DM trials\n",operations.ndm);
	}

	// Now we read the data file into memory, if it fits!
	data_array = pch_seek_read_file(header,scrunch_factor);
	if(data_array == NULL){
		// we cannot contiune... data couldn't be read or memory couldn't be allocated.
		fprintf(stderr,"Error, could not read data\n");
		return 1;
	}

#ifdef FFTW_THREADS
	// If we are using FFTW in multi-threaded mode, we initialise it here.
	if (threads){
		printf("Using %d threads\n",threads);
		fftwf_init_threads();
		fftwf_plan_with_nthreads(threads);
	}
#endif

	// call this function to do the work. 
	// The arrays passed are destroyed and free'd in the operation
	// of the search, so we don't need to free the data array.
	pch_seek_do_search(&operations,header,data_array);

#ifdef FFTW_THREADS
	if(threads){
		fftwf_cleanup_threads();
	}
#endif

	free(operations.dmtrials);
	if(operations.harmfolds!=NULL)free(operations.harmfolds);

	return 0;
}

